# Generated by Django 6.0.6 on 2026-07-02 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quest_1_progress', models.IntegerField(default=0)),
                ('quest_2_progress', models.IntegerField(default=0)),
                ('quest_3_progress', models.IntegerField(default=0)),
                ('quest_1_completed', models.BooleanField(default=False)),
                ('quest_2_completed', models.BooleanField(default=False)),
                ('quest_3_completed', models.BooleanField(default=False)),
                ('all_completed', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ежедневное задание',
                'verbose_name_plural': 'Ежедневные задания',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
