# Generated by Django 6.0.6 on 2026-07-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='processed_habits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
