# Generated by Django 6.0.6 on 2026-07-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quests', '0002_dailyquest_processed_habits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquest',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailyquest',
            name='rewarded',
        ),
    ]
