# Generated by Django 6.0.6 on 2026-07-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quests', '0003_alter_dailyquest_options_remove_dailyquest_rewarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquest',
            name='processed_habits',
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='quest_1_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='quest_2_rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='quest_3_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
