# Generated by Django 6.0.6 on 2026-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quests', '0004_remove_dailyquest_processed_habits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='all_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
