# Generated by Django 6.0.6 on 2026-07-05 14:56

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_quests', '0005_dailyquest_all_rewarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['user', 'date'], name='daily_quest_user_id_32bf6a_idx'),
        ),
    ]
