# Generated by Django 6.0.6 on 2026-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('price', models.IntegerField(verbose_name='Цена (в золоте)')),
            ],
            options={
                'verbose_name': 'Скин',
                'verbose_name_plural': 'Скины',
                'ordering': ['price'],
            },
        ),
    ]
