# Generated by Django 6.0.6 on 2026-07-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_skin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skin',
        ),
    ]
