# Generated by Django 6.0.6 on 2026-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owned_skins',
            field=models.JSONField(default=list, verbose_name='Купленные скины'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_skin',
            field=models.CharField(default='😊', max_length=50, verbose_name='Скин аватара'),
        ),
    ]
