# Generated by Django 6.0.6 on 2026-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_owned_skins_alter_user_avatar_skin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_completed',
            field=models.IntegerField(default=0, verbose_name='Всего выполнено привычек'),
        ),
    ]
