# Generated by Django 6.0.6 on 2026-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_total_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_skins',
            field=models.JSONField(default=list),
        ),
    ]
