# Generated by Django 6.0.6 on 2026-07-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_selected_skins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='health',
        ),
        migrations.RemoveField(
            model_name='user',
            name='selected_skins',
        ),
    ]
