# Generated by Django 6.0.6 on 2026-07-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_health_remove_user_selected_skins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_completed',
        ),
    ]
