# Generated by Django 6.0.6 on 2026-07-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_total_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_completed',
            field=models.IntegerField(default=0),
        ),
    ]
