# Generated by Django 6.0.6 on 2026-07-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_total_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_completed',
        ),
    ]
